### ISSUE TITLE
Question about relation between 【localization potential】 and【low-resolution-Long-term Fusion】

### ISSUE THREAD

**Issue by wnov** [Divadi/SOLOFusion#1]
Great work! I have tried to read carefully, and got some question.
`low-resolution-Long-term Fusion` is performed after depth prediction, why can it still benefit from `localization potential` with long term history frame?
Maybe there are some misunderstanding, but it realy confuse me yet.

**Comment by Divadi** [comment]
Although long-term fusion is performed after per-frame depth prediction, the BEV map itself is a cost volume that seeks to localize objects. Since the depth prediction is soft (a probability distribution over depths), not hard (a single scalar per pixel), errors in the initial depth prediction can be fixed in the BEV map using long-term fusion, benefitting localization potential.
