### ISSUE TITLE
Question about history_bev

### ISSUE THREAD

**Issue by TmacTmac1992** [Divadi/SOLOFusion#11]
Hi Author, 

I have a question about history_bev. 
The history_bev is calculated from last iter and is detached.  
However,  the weight of img branch is changed ever iter,  the history_bev stored previous and the history_bev calculate by img_branch(current iter) is different, will this bring issue to the model?

**Comment by Divadi** [comment]
There might be some feature mismatch between training steps, but as the model starts to converge, it should be less of a problem. Likely the phase1 training mitigates this problem to a certain extent.

We do this because re-calculating the BEV feature for past timesteps at every new training batch is very expensive and will slow down the training by multiple times; perhaps if training time is not an issue, this can be considered.
