### ISSUE TITLE
Question about resnet50 results

### ISSUE THREAD

**Issue by swtju14** [Divadi/SOLOFusion#3]
Hi, in your table, resnet-50 mAP/NDS: 42.7/53.4，but According to the calculation rules of NDS, the real NDS is 54.4. Is it a printing error? 
<img width="717" alt="截屏2023-03-05 下午3 25 25" src="https://user-images.githubusercontent.com/46061397/222947809-91dc706d-91ea-472a-9fc3-3e9c1c8e7a54.png">

**Comment by Divadi** [comment]
Thank you for pointing this out. Upon re-visiting my experiments, I found that had copied down the evaluation result for mAOE incorrectly - it should instead be 0.511. We sincerely regret this mistake and it will be fixed in the updated paper. For insight into why this may be the case, please reference the analysis on static vs moving objects in the OpenReview supplementary. We do note, however, that the larger ResNet101 model achieves similar mAOE performance as baselines, and we generally find that mAOE is strongly correlated with strength of backbone and 2D-view pre-training.

**Comment by swtju14** [comment]
Hi, Thanks for your response. I have another question.
1. In your table, resnet-101 without cbgs as baseline, mAOE only achieves 0.604. Does this backbone use 2D-view pre-training? 

![截屏2023-03-06 上午10 48 31](https://user-images.githubusercontent.com/46061397/223008138-21377f03-53c3-4867-bf81-21fc94315dc6.png)

**Comment by Divadi** [comment]
It does not - The ResNet101 backbone here just uses ImageNet pre-training. I believe that is one of the main reasons the mAOE result is poor. The other methods' backbones, including FCOS3D pre-training, has seen a lot more data at this point.

**Comment by swtju14** [comment]
Yes. In our reproduced code, I have the same AOE performance, but our mAP can not achieve 0.472. Resnet-101 with cbgs as baseline,  mAOE achieves 0.381. Does this backbone use 2D-view pre-training? 
Our papers require cite your results, so I want to know this details, Thanks for your response.

![截屏2023-03-06 上午11 54 13](https://user-images.githubusercontent.com/46061397/223015955-947fe518-2db0-47fb-b60d-0abe184c548a.png)

**Comment by Divadi** [comment]
Thank you for your interest in our work. 2D-view pre-training is not used. Over the training duration, mAOE consistently decreases to 0.381. 

I will try to release the code shortly after ICCV deadline.
